### ISSUE TITLE
About PDK Information

### ISSUE THREAD

**Issue by swleungbrian** [UNSAMDCI/PDK_ONC5#2]
Dear Sir,

Could you provide the PDK information in order to run the tcl scripts for ICC?

Regards,

Brian

**Comment by kuoyaoming93** [comment]
Hi, 

the process used is [OnSemi C5](https://www.onsemi.com/site/pdf/C5-D.PDF)
PDK is confidential, you should ask access to the foundry.

Best Regards, 
Yao-Ming
